from __future__ import annotations

from typing import List


def build_iteration_gating_summary(
    mode: str,
    params: str,
    sampled_ids: List[int],
    gate_results: List[dict],
    visibility_stats: dict,
    grad_stats: dict,
    spgm_stats: dict | None = None,
) -> dict:
    accepted_ids = [int(item['sample_id']) for item in gate_results if item.get('weight', 0.0) > 0]
    rejected = [item for item in gate_results if item.get('weight', 0.0) <= 0]
    rejected_ids = [int(item['sample_id']) for item in rejected]
    rejected_reasons = {str(int(item['sample_id'])): list(item.get('reasons', [])) for item in rejected if item.get('reasons')}
    accepted_signal_weights = {str(int(item['sample_id'])): float(item.get('weight', 0.0)) for item in gate_results if item.get('weight', 0.0) > 0}
    metrics = {
        str(int(item['sample_id'])): dict(item.get('metrics', {}))
        for item in gate_results
    }

    summary = {
        'pseudo_local_gating_mode': mode,
        'pseudo_local_gating_params': params,
        'sampled_pseudo_sample_ids': [int(x) for x in sampled_ids],
        'accepted_pseudo_sample_ids': accepted_ids,
        'rejected_pseudo_sample_ids': rejected_ids,
        'rejected_reasons': rejected_reasons,
        'accepted_signal_weights': accepted_signal_weights,
        'sample_signal_metrics': metrics,
        # Legacy visibility-union fields (None for SPGM modes)
        'visible_union_ratio': visibility_stats.get('visible_union_ratio') if visibility_stats else None,
        'visible_union_weight_mean': visibility_stats.get('visible_union_weight_mean') if visibility_stats else None,
        'accepted_visibility_count': visibility_stats.get('accepted_count') if visibility_stats else None,
        # Grad stats (common to both modes)
        'grad_keep_ratio_xyz': grad_stats.get('grad_keep_ratio_xyz'),
        'grad_keep_ratio_opacity': grad_stats.get('grad_keep_ratio_opacity'),
        'grad_weight_mean_xyz': grad_stats.get('grad_weight_mean_xyz'),
        'grad_weight_mean_opacity': grad_stats.get('grad_weight_mean_opacity'),
        'grad_norm_xyz_pre_mask': grad_stats.get('grad_norm_xyz_pre_mask'),
        'grad_norm_xyz_post_mask': grad_stats.get('grad_norm_xyz_post_mask'),
        'grad_norm_opacity_pre_mask': grad_stats.get('grad_norm_opacity_pre_mask'),
        'grad_norm_opacity_post_mask': grad_stats.get('grad_norm_opacity_post_mask'),
    }

    spgm_fields = {
        'spgm_active_ratio': None,
        'spgm_selected_ratio': None,
        'spgm_policy_mode_effective': None,
        'spgm_ranking_mode_effective': None,
        'spgm_accepted_view_count': None,
        'spgm_support_mean': None,
        'spgm_support_p50': None,
        'spgm_support_max': None,
        'spgm_depth_entropy': None,
        'spgm_density_entropy': None,
        'spgm_importance_mean': None,
        'spgm_importance_p50': None,
        'spgm_ranking_score_mean': None,
        'spgm_ranking_score_p50': None,
        'spgm_support_norm_mean': None,
        'spgm_weight_mean': None,
        'spgm_weight_p10': None,
        'spgm_weight_p50': None,
        'spgm_weight_p90': None,
        'spgm_cluster_count_near': None,
        'spgm_cluster_count_mid': None,
        'spgm_cluster_count_far': None,
        'spgm_selected_count_near': None,
        'spgm_selected_count_mid': None,
        'spgm_selected_count_far': None,
        'spgm_density_mode_effective': None,
        'spgm_state_score_mean': None,
        'spgm_state_score_p50': None,
        'spgm_participation_score_mean': None,
        'spgm_participation_score_p50': None,
        'spgm_state_score_mean_near': None,
        'spgm_state_score_mean_mid': None,
        'spgm_state_score_mean_far': None,
        'spgm_state_score_p50_near': None,
        'spgm_state_score_p50_mid': None,
        'spgm_state_score_p50_far': None,
        'spgm_participation_score_mean_near': None,
        'spgm_participation_score_mean_mid': None,
        'spgm_participation_score_mean_far': None,
        'spgm_participation_score_p50_near': None,
        'spgm_participation_score_p50_mid': None,
        'spgm_participation_score_p50_far': None,
        'spgm_population_support_mean': None,
        'spgm_struct_density_mean': None,
        'spgm_manager_mode_effective': None,
        'spgm_state_action_applied': None,
        'spgm_state_xyz_scale_mean': None,
        'spgm_state_xyz_scale_mean_near': None,
        'spgm_state_xyz_scale_mean_mid': None,
        'spgm_state_xyz_scale_mean_far': None,
        'spgm_state_grad_norm_xyz_pre_state': None,
        'spgm_state_grad_norm_xyz_post_state': None,
        'spgm_state_lr_scale_near': None,
        'spgm_state_lr_scale_mid': None,
        'spgm_state_lr_scale_far': None,
        'spgm_state_opacity_decay_near': None,
        'spgm_state_opacity_decay_mid': None,
        'spgm_state_opacity_decay_far': None,
        'spgm_state_opacity_scale_mean': None,
        'spgm_state_opacity_scale_mean_near': None,
        'spgm_state_opacity_scale_mean_mid': None,
        'spgm_state_opacity_scale_mean_far': None,
        'spgm_state_candidate_count_near': None,
        'spgm_state_candidate_count_mid': None,
        'spgm_state_candidate_count_far': None,
        'spgm_state_participation_ratio': None,
        'spgm_state_participation_ratio_near': None,
        'spgm_state_participation_ratio_mid': None,
        'spgm_state_participation_ratio_far': None,
        'spgm_state_participation_drop_count_near': None,
        'spgm_state_participation_drop_count_mid': None,
        'spgm_state_participation_drop_count_far': None,
    }

    if spgm_stats:
        spgm_fields.update({
            'spgm_active_ratio': spgm_stats.get('active_ratio'),
            'spgm_selected_ratio': spgm_stats.get('selected_ratio'),
            'spgm_policy_mode_effective': spgm_stats.get('policy_mode_effective'),
            'spgm_ranking_mode_effective': spgm_stats.get('ranking_mode_effective'),
            'spgm_accepted_view_count': spgm_stats.get('accepted_view_count'),
            'spgm_support_mean': spgm_stats.get('support_mean'),
            'spgm_support_p50': spgm_stats.get('support_p50'),
            'spgm_support_max': spgm_stats.get('support_max'),
            'spgm_depth_entropy': spgm_stats.get('depth_entropy'),
            'spgm_density_entropy': spgm_stats.get('density_entropy'),
            'spgm_importance_mean': spgm_stats.get('importance_mean'),
            'spgm_importance_p50': spgm_stats.get('importance_p50'),
            'spgm_ranking_score_mean': spgm_stats.get('ranking_score_mean'),
            'spgm_ranking_score_p50': spgm_stats.get('ranking_score_p50'),
            'spgm_support_norm_mean': spgm_stats.get('support_norm_mean'),
            'spgm_weight_mean': spgm_stats.get('weight_mean'),
            'spgm_weight_p10': spgm_stats.get('weight_p10'),
            'spgm_weight_p50': spgm_stats.get('weight_p50'),
            'spgm_weight_p90': spgm_stats.get('weight_p90'),
            'spgm_cluster_count_near': spgm_stats.get('cluster_count_near'),
            'spgm_cluster_count_mid': spgm_stats.get('cluster_count_mid'),
            'spgm_cluster_count_far': spgm_stats.get('cluster_count_far'),
            'spgm_selected_count_near': spgm_stats.get('selected_count_near'),
            'spgm_selected_count_mid': spgm_stats.get('selected_count_mid'),
            'spgm_selected_count_far': spgm_stats.get('selected_count_far'),
            'spgm_density_mode_effective': spgm_stats.get('density_mode_effective'),
            'spgm_state_score_mean': spgm_stats.get('state_score_mean'),
            'spgm_state_score_p50': spgm_stats.get('state_score_p50'),
            'spgm_participation_score_mean': spgm_stats.get('participation_score_mean'),
            'spgm_participation_score_p50': spgm_stats.get('participation_score_p50'),
            'spgm_state_score_mean_near': spgm_stats.get('state_score_mean_near'),
            'spgm_state_score_mean_mid': spgm_stats.get('state_score_mean_mid'),
            'spgm_state_score_mean_far': spgm_stats.get('state_score_mean_far'),
            'spgm_state_score_p50_near': spgm_stats.get('state_score_p50_near'),
            'spgm_state_score_p50_mid': spgm_stats.get('state_score_p50_mid'),
            'spgm_state_score_p50_far': spgm_stats.get('state_score_p50_far'),
            'spgm_participation_score_mean_near': spgm_stats.get('participation_score_mean_near'),
            'spgm_participation_score_mean_mid': spgm_stats.get('participation_score_mean_mid'),
            'spgm_participation_score_mean_far': spgm_stats.get('participation_score_mean_far'),
            'spgm_participation_score_p50_near': spgm_stats.get('participation_score_p50_near'),
            'spgm_participation_score_p50_mid': spgm_stats.get('participation_score_p50_mid'),
            'spgm_participation_score_p50_far': spgm_stats.get('participation_score_p50_far'),
            'spgm_population_support_mean': spgm_stats.get('population_support_mean'),
            'spgm_struct_density_mean': spgm_stats.get('struct_density_mean'),
            'spgm_manager_mode_effective': spgm_stats.get('manager_mode_effective'),
            'spgm_state_action_applied': spgm_stats.get('state_action_applied'),
            'spgm_state_xyz_scale_mean': spgm_stats.get('state_xyz_scale_mean'),
            'spgm_state_xyz_scale_mean_near': spgm_stats.get('state_xyz_scale_mean_near'),
            'spgm_state_xyz_scale_mean_mid': spgm_stats.get('state_xyz_scale_mean_mid'),
            'spgm_state_xyz_scale_mean_far': spgm_stats.get('state_xyz_scale_mean_far'),
            'spgm_state_grad_norm_xyz_pre_state': spgm_stats.get('state_grad_norm_xyz_pre_state'),
            'spgm_state_grad_norm_xyz_post_state': spgm_stats.get('state_grad_norm_xyz_post_state'),
            'spgm_state_lr_scale_near': spgm_stats.get('state_lr_scale_near'),
            'spgm_state_lr_scale_mid': spgm_stats.get('state_lr_scale_mid'),
            'spgm_state_lr_scale_far': spgm_stats.get('state_lr_scale_far'),
            'spgm_state_opacity_decay_near': spgm_stats.get('state_opacity_decay_near'),
            'spgm_state_opacity_decay_mid': spgm_stats.get('state_opacity_decay_mid'),
            'spgm_state_opacity_decay_far': spgm_stats.get('state_opacity_decay_far'),
            'spgm_state_opacity_scale_mean': spgm_stats.get('state_opacity_scale_mean'),
            'spgm_state_opacity_scale_mean_near': spgm_stats.get('state_opacity_scale_mean_near'),
            'spgm_state_opacity_scale_mean_mid': spgm_stats.get('state_opacity_scale_mean_mid'),
            'spgm_state_opacity_scale_mean_far': spgm_stats.get('state_opacity_scale_mean_far'),
            'spgm_state_candidate_count_near': spgm_stats.get('state_candidate_count_near'),
            'spgm_state_candidate_count_mid': spgm_stats.get('state_candidate_count_mid'),
            'spgm_state_candidate_count_far': spgm_stats.get('state_candidate_count_far'),
            'spgm_state_participation_ratio': spgm_stats.get('state_participation_ratio'),
            'spgm_state_participation_ratio_near': spgm_stats.get('state_participation_ratio_near'),
            'spgm_state_participation_ratio_mid': spgm_stats.get('state_participation_ratio_mid'),
            'spgm_state_participation_ratio_far': spgm_stats.get('state_participation_ratio_far'),
            'spgm_state_participation_drop_count_near': spgm_stats.get('state_participation_drop_count_near'),
            'spgm_state_participation_drop_count_mid': spgm_stats.get('state_participation_drop_count_mid'),
            'spgm_state_participation_drop_count_far': spgm_stats.get('state_participation_drop_count_far'),
        })

    summary.update(spgm_fields)
    return summary
